// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Roslynator", "RCS1077:Optimize LINQ method call", Justification = "<Pending>", Scope = "member", Target = "~M:PraiseCMS.DataAccess.DAL.AdoDataAccess.ReadPermissionsByModulesAndUserId(System.Collections.Generic.List{PraiseCMS.DataAccess.Models.Modules},System.Collections.Generic.List{PraiseCMS.DataAccess.Models.ApplicationRoles},System.String)~System.Collections.Generic.List{PraiseCMS.DataAccess.Models.Permissions}")]
[assembly: SuppressMessage("Roslynator", "RCS1077:Optimize LINQ method call", Justification = "<Pending>", Scope = "member", Target = "~M:PraiseCMS.DataAccess.DAL.AdoDataAccess.ReadPermittedModulesByRolesAndUserId(System.Collections.Generic.List{PraiseCMS.DataAccess.Models.ApplicationRoles},System.String)~System.Collections.Generic.List{PraiseCMS.DataAccess.Models.Modules}")]
[assembly: SuppressMessage("Roslynator", "RCS1077:Optimize LINQ method call", Justification = "<Pending>", Scope = "member", Target = "~M:PraiseCMS.DataAccess.Mapper.Mapper.Map(System.Collections.Generic.List{PraiseCMS.DataAccess.Models.OfflineGiving})~System.Collections.Generic.List{PraiseCMS.DataAccess.Models.ViewModels.MyGivingVM}")]
[assembly: SuppressMessage("Roslynator", "RCS1077:Optimize LINQ method call", Justification = "<Pending>", Scope = "member", Target = "~M:PraiseCMS.DataAccess.Mapper.Mapper.Map(System.Collections.Generic.List{PraiseCMS.DataAccess.Models.Payment})~System.Collections.Generic.List{PraiseCMS.DataAccess.Models.ViewModels.MyGivingVM}")]
[assembly: SuppressMessage("Roslynator", "RCS1077:Optimize LINQ method call", Justification = "<Pending>", Scope = "member", Target = "~M:PraiseCMS.DataAccess.Mapper.Mapper.MapPaymentsSummary(System.Collections.Generic.List{PraiseCMS.DataAccess.Models.Payment})~System.Collections.Generic.List{PraiseCMS.DataAccess.Models.ViewModels.ChurchPaymentsVM}")]
[assembly: SuppressMessage("Roslynator", "RCS1077:Optimize LINQ method call", Justification = "<Pending>", Scope = "member", Target = "~M:PraiseCMS.DataAccess.Shared.Utilities.GetAccessLevel(System.String,System.Collections.Generic.IEnumerable{PraiseCMS.DataAccess.Models.Permissions})~System.Int32")]
[assembly: SuppressMessage("Roslynator", "RCS1077:Optimize LINQ method call", Justification = "<Pending>", Scope = "member", Target = "~M:PraiseCMS.DataAccess.Shared.Utilities.GetAccessLevelPermission(System.String,System.Collections.Generic.IEnumerable{PraiseCMS.DataAccess.Models.Permissions})~PraiseCMS.DataAccess.Models.Permissions")]
[assembly: SuppressMessage("Roslynator", "RCS1077:Optimize LINQ method call", Justification = "<Pending>", Scope = "member", Target = "~M:PraiseCMS.DataAccess.Shared.Utilities.GetCurrentReports(System.String,System.String)~System.Collections.Generic.List{PraiseCMS.DataAccess.Models.ReportCategory}")]
[assembly: SuppressMessage("Roslynator", "RCS1077:Optimize LINQ method call", Justification = "<Pending>", Scope = "member", Target = "~P:PraiseCMS.DataAccess.Session.SessionVariables.Widgets")]
[assembly: SuppressMessage("Roslynator", "RCS1077:Optimize LINQ method call", Justification = "<Pending>", Scope = "member", Target = "~M:PraiseCMS.DataAccess.Shared.Utilities.GetDefaultWidgetSortable(System.String,System.Collections.Generic.List{System.String})~System.Collections.Generic.List{PraiseCMS.DataAccess.Models.WidgetSortable}")]
